#!/usr/bin/env python3
"""3D Terrain Visualization dari DEM GeoTIFF"""

import sys
import argparse
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def render_3d(dem_path, output_path, title="3D Terrain", exaggeration=2.0):
    try:
        import rasterio
        with rasterio.open(dem_path) as src:
            dem = src.read(1)
            transform = src.transform
            
        max_safe_dim = 1000 # Optimized for CPU (i7) without GPU
        if dem.shape[0] > max_safe_dim or dem.shape[1] > max_safe_dim:
            print(f"[WARNING] Matriks terlalu besar ({dem.shape}). Menurunkan resolusi ke max {max_safe_dim} agar tidak OOM...")
            factor = max(dem.shape[0] // max_safe_dim, dem.shape[1] // max_safe_dim, 1)
            dem = dem[::factor, ::factor]
        
        # Handle nodata
        dem = np.where(dem < -9000, np.nan, dem)
        dem = np.where(np.isnan(dem), np.nanmin(dem), dem)
        
        rows, cols = dem.shape
        x = np.arange(0, cols)
        y = np.arange(0, rows)
        x, y = np.meshgrid(x, y)
        
        fig = plt.figure(figsize=(16, 12))
        ax = fig.add_subplot(111, projection='3d')
        
        # Color map berdasarkan elevasi
        colors = plt.cm.gist_earth((dem - np.nanmin(dem)) / (np.nanmax(dem) - np.nanmin(dem) + 0.001))
        
        # Render optimization for CPU: antialiased=False, larger stride
        ax.plot_surface(x, y, dem * exaggeration, facecolors=colors, 
                       rstride=2, cstride=2, antialiased=False, shade=True)
        
        # Layout ala Peta Kartografi untuk 3D
        fig.patch.set_facecolor('#f8f9fa')  # Latar belakang peta cerah
        ax.set_facecolor('#f8f9fa')
        
        # Tambahkan 3D Contour di bawah (offset di dasar)
        ax.contour(x, y, dem * exaggeration, zdir='z', offset=np.nanmin(dem)*exaggeration - 10, 
                   levels=15, cmap='gist_earth', alpha=0.5)
        
        # Kop Peta 3D
        fig.text(0.5, 0.95, "PETA TOPOGRAFI 3D DEMNAS", 
                 fontsize=22, fontweight='bold', ha='center', color='#2c3e50')
        fig.text(0.5, 0.91, title, 
                 fontsize=14, ha='center', color='#34495e')
        
        ax.set_xlabel('Grid X (pixel)', labelpad=15)
        ax.set_ylabel('Grid Y (pixel)', labelpad=15)
        ax.set_zlabel(f'Elevasi (m) Skala x{exaggeration}', labelpad=15)
        
        # Legend / Info Kotak di pojok
        info_text = (
            f"Statistik Topografi:\n"
            f"Elevasi Minimum : {np.nanmin(dem):.1f} m\n"
            f"Elevasi Maksimum: {np.nanmax(dem):.1f} m\n"
            f"Z-Exaggeration  : {exaggeration}x\n"
            f"Resolusi Grid   : {cols} x {rows}\n"
            f"\nSumber Data: Badan Informasi Geospasial\n"
            f"Generated by: Rizki Agustiawan x ZeroClaw AI"
        )
        
        # Kotak info di kiri bawah
        props = dict(boxstyle='round,pad=1', facecolor='white', alpha=0.9, edgecolor='#bdc3c7')
        fig.text(0.05, 0.05, info_text, fontsize=10, 
                 verticalalignment='bottom', bbox=props, family='monospace')
        
        # Colorbar Elevasi
        import matplotlib as mpl
        cb_ax = fig.add_axes([0.85, 0.2, 0.02, 0.5]) # [x, y, width, height]
        norm = mpl.colors.Normalize(vmin=np.nanmin(dem), vmax=np.nanmax(dem))
        cb = plt.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap='gist_earth'), 
                          cax=cb_ax, orientation='vertical')
        cb.set_label('Elevasi (meter dpl)', fontsize=12, fontweight='bold')
        
        ax.view_init(elev=45, azim=230) # Sudut pandang yang lebih baik untuk melihat alas
        
        # Hide grid lines and planes for cleaner map look
        ax.xaxis.pane.fill = False
        ax.yaxis.pane.fill = False
        ax.zaxis.pane.fill = False
        ax.grid(False)
        
        plt.savefig(output_path, dpi=200, bbox_inches='tight')
        plt.close()
        
        return f"SUCCESS: 3D terrain disimpan di {output_path}"
        
    except Exception as e:
        return f"ERROR: {str(e)}"

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dem", required=True, help="Path ke DEM GeoTIFF")
    parser.add_argument("--output", required=True, help="Output PNG path")
    parser.add_argument("--title", default="3D Terrain Visualization")
    parser.add_argument("--exaggeration", type=float, default=2.0)
    args = parser.parse_args()
    
    print(render_3d(args.dem, args.output, args.title, args.exaggeration))
