#!/usr/bin/env python3
"""3D Terrain Visualization dari DEM GeoTIFF"""

import sys
import argparse
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def render_3d(dem_path, output_path, title="3D Terrain", exaggeration=2.0):
    try:
        import rasterio
        with rasterio.open(dem_path) as src:
            dem = src.read(1)
            transform = src.transform
            
        # Downsample jika terlalu besar (max 500x500 untuk performa)
        max_dim = 500
        if dem.shape[0] > max_dim or dem.shape[1] > max_dim:
            factor = max(dem.shape[0] // max_dim, dem.shape[1] // max_dim, 1)
            dem = dem[::factor, ::factor]
        
        # Handle nodata
        dem = np.where(dem < -9000, np.nan, dem)
        dem = np.where(np.isnan(dem), np.nanmin(dem), dem)
        
        rows, cols = dem.shape
        x = np.arange(0, cols)
        y = np.arange(0, rows)
        x, y = np.meshgrid(x, y)
        
        fig = plt.figure(figsize=(16, 12))
        ax = fig.add_subplot(111, projection='3d')
        
        # Color map berdasarkan elevasi
        colors = plt.cm.terrain((dem - np.nanmin(dem)) / (np.nanmax(dem) - np.nanmin(dem) + 0.001))
        
        ax.plot_surface(x, y, dem * exaggeration, facecolors=colors, 
                       rstride=1, cstride=1, antialiased=True, shade=True)
        
        ax.set_title(title, fontsize=16, fontweight='bold', pad=20)
        ax.set_xlabel('Column (pixel)')
        ax.set_ylabel('Row (pixel)')
        ax.set_zlabel(f'Elevation (m) x{exaggeration}')
        
        # Info text
        fig.text(0.02, 0.02, 
                f'Min: {np.nanmin(dem):.0f}m | Max: {np.nanmax(dem):.0f}m | '
                f'Size: {rows}x{cols} | Exaggeration: {exaggeration}x\n'
                f'Generated by ZeroClaw Environmental AI',
                fontsize=9, style='italic')
        
        ax.view_init(elev=35, azim=225)
        
        plt.savefig(output_path, dpi=200, bbox_inches='tight')
        plt.close()
        
        return f"SUCCESS: 3D terrain disimpan di {output_path}"
        
    except Exception as e:
        return f"ERROR: {str(e)}"

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dem", required=True, help="Path ke DEM GeoTIFF")
    parser.add_argument("--output", required=True, help="Output PNG path")
    parser.add_argument("--title", default="3D Terrain Visualization")
    parser.add_argument("--exaggeration", type=float, default=2.0)
    args = parser.parse_args()
    
    print(render_3d(args.dem, args.output, args.title, args.exaggeration))
