# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_inference_pb2 as ai__inference__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceEngineStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictFloodFNO = channel.unary_unary(
                '/ai_inference.InferenceEngine/PredictFloodFNO',
                request_serializer=ai__inference__pb2.FloodRequest.SerializeToString,
                response_deserializer=ai__inference__pb2.FloodResponse.FromString,
                _registered_method=True)
        self.PredictGroundwaterPINN = channel.unary_unary(
                '/ai_inference.InferenceEngine/PredictGroundwaterPINN',
                request_serializer=ai__inference__pb2.GroundwaterRequest.SerializeToString,
                response_deserializer=ai__inference__pb2.GroundwaterResponse.FromString,
                _registered_method=True)
        self.PredictShallowWaterPINO = channel.unary_unary(
                '/ai_inference.InferenceEngine/PredictShallowWaterPINO',
                request_serializer=ai__inference__pb2.ShallowWaterRequest.SerializeToString,
                response_deserializer=ai__inference__pb2.ShallowWaterResponse.FromString,
                _registered_method=True)


class InferenceEngineServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictFloodFNO(self, request, context):
        """FNO macro-scale flood/weather prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictGroundwaterPINN(self, request, context):
        """PINN micro-scale groundwater/contaminant prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictShallowWaterPINO(self, request, context):
        """PINO macro-scale shallow water prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictFloodFNO': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictFloodFNO,
                    request_deserializer=ai__inference__pb2.FloodRequest.FromString,
                    response_serializer=ai__inference__pb2.FloodResponse.SerializeToString,
            ),
            'PredictGroundwaterPINN': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictGroundwaterPINN,
                    request_deserializer=ai__inference__pb2.GroundwaterRequest.FromString,
                    response_serializer=ai__inference__pb2.GroundwaterResponse.SerializeToString,
            ),
            'PredictShallowWaterPINO': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictShallowWaterPINO,
                    request_deserializer=ai__inference__pb2.ShallowWaterRequest.FromString,
                    response_serializer=ai__inference__pb2.ShallowWaterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_inference.InferenceEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_inference.InferenceEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceEngine:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictFloodFNO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.InferenceEngine/PredictFloodFNO',
            ai__inference__pb2.FloodRequest.SerializeToString,
            ai__inference__pb2.FloodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictGroundwaterPINN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.InferenceEngine/PredictGroundwaterPINN',
            ai__inference__pb2.GroundwaterRequest.SerializeToString,
            ai__inference__pb2.GroundwaterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictShallowWaterPINO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.InferenceEngine/PredictShallowWaterPINO',
            ai__inference__pb2.ShallowWaterRequest.SerializeToString,
            ai__inference__pb2.ShallowWaterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
